In [24]:
import os

In [6]:
import pandas as pd
import numpy as np

In [8]:
os.getcwd()

'C:\\Users\\elflo\\Desktop\\jupyter'

In [22]:
data_df=pd.read_csv('C:\\Users\\elflo\\Desktop\\jupyter\\finalsb.csv')

In [23]:
data_df.head()

,ID,NAME,F1C011,F1C012,F1C021,F1C022,F1C031,F1C032,F1C051,F1C052,...,F1E15,F1E151,F1E152,F1E16,F1E161,F1E162,F1E17,F1E171,F1E172,Gradrate
0,100654,Alabama A & M University,40721719,22450482,12843275,5156941,17011985,6238927,8352837,4008167,...,0,0,0,0,0,0,24138036,24138036,0,11.211129
1,100663,University of Alabama at Birmingham,297402764,201713260,340868357,158080180,200468331,85995925,161643081,122571824,...,15793,15793,0,7474791,7474791,0,55841722,54070439,1771283,42.091999
2,100706,University of Alabama in Huntsville,70504706,43811274,111733437,57397883,10130820,3288361,13659301,7021899,...,0,0,0,980953,961334,19619,39758083,37821705,1936378,35.282650
3,100724,Alabama State University,36994782,23249888,3647276,1350568,3570270,1708191,12717006,4905746,...,0,0,0,0,0,0,16741726,14483380,2258346,10.139165
4,100751,The University of Alabama,312776287,182296415,118097592,55331292,57449310,30494764,112389476,49914976,...,0,0,0,12898997,12898997,0,236133124,225180763,10952361,52.643326

In [25]:
print(data_df.dtypes)

ID            int64
NAME         object
F1C011        int64
F1C012        int64
F1C021        int64
F1C022        int64
F1C031        int64
F1C032        int64
F1C051        int64
F1C052        int64
F1C061        int64
F1C062        int64
F1C071        int64
F1C072        int64
F1C101        int64
F1C111        int64
F1C112        int64
F1C121        int64
F1C122        int64
F1C131        int64
F1C132        int64
F1E01         int64
F1E02         int64
F1E03         int64
F1E04         int64
F1E05         int64
F1E06         int64
F1E07         int64
F1E08         int64
F1E09         int64
F1E10         int64
F1E11         int64
F1E12         int64
F1E121        int64
F1E122        int64
F1E13         int64
F1E131        int64
F1E132        int64
F1E14         int64
F1E141        int64
F1E142        int64
F1E15         int64
F1E151        int64
F1E152        int64
F1E16         int64
F1E161        int64
F1E162        int64
F1E17         int64
F1E171        int64
F1E172        int64
Gradrate    float64
dtype: object

In [26]:
data_df.describe()

,ID,F1C011,F1C012,F1C021,F1C022,F1C031,F1C032,F1C051,F1C052,F1C061,...,F1E15,F1E151,F1E152,F1E16,F1E161,F1E162,F1E17,F1E171,F1E172,Gradrate
count,525.000000,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,...,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,525.000000
mean,186533.354286,1.476554e+08,8.803705e+07,6.805215e+07,3.038921e+07,2.614694e+07,1.211209e+07,4.631783e+07,2.189055e+07,2.564042e+07,...,1.416414e+05,1.342081e+05,7.433318e+03,3.892099e+06,3.613406e+06,2.786934e+05,2.351228e+07,2.179753e+07,1.714747e+06,34.528930
std,58150.688431,2.369065e+08,1.407582e+08,1.679363e+08,7.538190e+07,7.831025e+07,4.341514e+07,9.285913e+07,4.349850e+07,2.961322e+07,...,1.204165e+06,1.159811e+06,1.084597e+05,9.965082e+06,9.401194e+06,1.031167e+06,4.147031e+07,3.981013e+07,3.334031e+06,16.998258
min,100654.000000,3.396034e+06,2.701773e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.426500e+05,3.241940e+05,7.300020e+05,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.040816
25%,153603.000000,3.218807e+07,1.773804e+07,4.879420e+05,1.739560e+05,9.733870e+05,4.415080e+05,7.181745e+06,3.321748e+06,8.019215e+06,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.540065e+06,2.054202e+06,0.000000e+00,22.627737
50%,184782.000000,7.050471e+07,4.122906e+07,3.399165e+06,1.471184e+06,3.572446e+06,1.525000e+06,1.794448e+07,7.999252e+06,1.666905e+07,...,0.000000e+00,0.000000e+00,0.000000e+00,3.499120e+05,2.994640e+05,0.000000e+00,8.582213e+06,7.242558e+06,3.118530e+05,31.407942
75%,216010.000000,1.634871e+08,9.936526e+07,3.764400e+07,1.562418e+07,1.614513e+07,6.172644e+06,4.522440e+07,2.148000e+07,3.126180e+07,...,0.000000e+00,0.000000e+00,0.000000e+00,2.527893e+06,2.206830e+06,1.140670e+05,2.335537e+07,2.126059e+07,1.850000e+06,44.593910
max,490805.000000,2.885657e+09,1.635494e+09,1.140676e+09,5.675876e+08,8.897270e+08,5.584200e+08,1.052335e+09,5.074848e+08,2.801011e+08,...,2.236810e+07,2.236810e+07,2.252477e+06,8.961265e+07,8.855914e+07,1.516399e+07,4.167790e+08,4.056350e+08,3.460064e+07,88.610352

In [30]:
data_df.drop(["ID", "NAME"], axis=1, inplace = True)

data_df.describe()

,F1C011,F1C012,F1C021,F1C022,F1C031,F1C032,F1C051,F1C052,F1C061,F1C062,...,F1E15,F1E151,F1E152,F1E16,F1E161,F1E162,F1E17,F1E171,F1E172,Gradrate
count,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,...,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,5.250000e+02,525.000000
mean,1.476554e+08,8.803705e+07,6.805215e+07,3.038921e+07,2.614694e+07,1.211209e+07,4.631783e+07,2.189055e+07,2.564042e+07,1.151716e+07,...,1.416414e+05,1.342081e+05,7.433318e+03,3.892099e+06,3.613406e+06,2.786934e+05,2.351228e+07,2.179753e+07,1.714747e+06,34.528930
std,2.369065e+08,1.407582e+08,1.679363e+08,7.538190e+07,7.831025e+07,4.341514e+07,9.285913e+07,4.349850e+07,2.961322e+07,1.265338e+07,...,1.204165e+06,1.159811e+06,1.084597e+05,9.965082e+06,9.401194e+06,1.031167e+06,4.147031e+07,3.981013e+07,3.334031e+06,16.998258
min,3.396034e+06,2.701773e+06,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.426500e+05,3.241940e+05,7.300020e+05,3.961000e+05,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.040816
25%,3.218807e+07,1.773804e+07,4.879420e+05,1.739560e+05,9.733870e+05,4.415080e+05,7.181745e+06,3.321748e+06,8.019215e+06,3.633961e+06,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.540065e+06,2.054202e+06,0.000000e+00,22.627737
50%,7.050471e+07,4.122906e+07,3.399165e+06,1.471184e+06,3.572446e+06,1.525000e+06,1.794448e+07,7.999252e+06,1.666905e+07,7.455456e+06,...,0.000000e+00,0.000000e+00,0.000000e+00,3.499120e+05,2.994640e+05,0.000000e+00,8.582213e+06,7.242558e+06,3.118530e+05,31.407942
75%,1.634871e+08,9.936526e+07,3.764400e+07,1.562418e+07,1.614513e+07,6.172644e+06,4.522440e+07,2.148000e+07,3.126180e+07,1.461100e+07,...,0.000000e+00,0.000000e+00,0.000000e+00,2.527893e+06,2.206830e+06,1.140670e+05,2.335537e+07,2.126059e+07,1.850000e+06,44.593910
max,2.885657e+09,1.635494e+09,1.140676e+09,5.675876e+08,8.897270e+08,5.584200e+08,1.052335e+09,5.074848e+08,2.801011e+08,1.083031e+08,...,2.236810e+07,2.236810e+07,2.252477e+06,8.961265e+07,8.855914e+07,1.516399e+07,4.167790e+08,4.056350e+08,3.460064e+07,88.610352

In [31]:
data_df.corr()['Gradrate'].sort_values()

F1E152      0.018153
F1C131      0.032084
F1E151      0.039293
F1E15       0.039481
F1E04       0.083489
F1C132      0.107171
F1E142      0.131974
F1E122      0.165982
F1E01       0.169219
F1E121      0.187248
F1E132      0.197719
F1E12       0.201996
F1E141      0.229321
F1E14       0.234366
F1C032      0.274714
F1E131      0.275230
F1C122      0.275525
F1E13       0.278817
F1E03       0.279909
F1C121      0.284089
F1E02       0.311307
F1C031      0.327175
F1E162      0.343510
F1E172      0.346972
F1E11       0.399712
F1C101      0.399712
F1E09       0.419526
F1E161      0.432462
F1E16       0.443536
F1C061      0.459462
F1E05       0.462984
F1E171      0.480574
F1C062      0.484161
F1C051      0.485199
F1C052      0.485581
F1E17       0.489231
F1E06       0.494004
F1E07       0.499711
F1C112      0.501216
F1E08       0.510584
F1C022      0.522763
F1E10       0.525334
F1C021      0.526085
F1C011      0.535639
F1C012      0.539143
F1C071      0.554353
F1C072      0.562136
F1C111      0.586118
Gradrate    1.000000
Name: Gradrate, dtype: float64